package mapreduce

// our simplified version of MapReduce does not supply a key to the 
// Map function, as in Google's MapReduce paper; only a value,
// which is a portion of the input file's content
func WCMap(value string) []KeyValue {
}

// called once for each key generated by Map, with a list of that 
// key's values. should return a single output value for that key.
func WCReduce(key string, values []string) string {
}
